<?php

// autoload.php @generated by Composer


// require_once __DIR__ . '\autoload_real.php';

require_once __DIR__ . '/vendor/composer/autoload_real.php';
//c:\myself\vscodeWorkspace\portal-api\v2\application
return ComposerAutoloaderInitb417890ff28bb19c8c65139522656eb4::getLoader();


//require_once __DIR__ . '\composer\autoload_real.php';
// return ComposerAutoloaderInitb417890ff28bb19c8c65139522656eb4::getLoader();
